### ISSUE TITLE
DoDH Quest Completion Tracker

### ISSUE THREAD

**Issue by xackery** [xackery/peq-expansions#14]
##
Corathus (corathus) - starts indiff to Dark Elf
- [ ] Gnome camp near Nek zone in
- [ ] Gnome camp tasks
- [ ] Treddlehoop - access to dreadspire keep http://everquest.allakhazam.com/db/quest.html?quest=3203 https://eq.magelo.com/npc/7682
- [ ] Aggro dialog of NPCs
##
corathusa
##
corathusb
##
illsalin
##
illsalina
##
illsalinb
##
illsalinc
##
dreadspire
##
drachnidhive
##
drachnidhivea
##
drachnidhiveb
##
drachnidhivec
##
westkorlach
##
westkorlacha
##
westkorlachb
##
westkorlachc
##
shadowspine
##
The Underquerry (eastkorlach) - starts dubious to Dark Elf
- [ ] Slavers near corathus zone in
- [ ] Slavers tasks
- [ ] Aggro dialog of NPCs
##
eastkorlacha

**Comment by xackery** [comment]
Moved to wiki page https://github.com/xackery/peq-expansions/wiki/Depths-of-Darkhollow
